### ISSUE TITLE
New update feedback

### ISSUE THREAD

**Issue by th3fallen** [protoloft/klipper_z_calibration#1]
1. document which config values are used far which moves, or add them to be overwritten in the zcalibrate config section
2. allow user to overwrite probe sample's for z calibration independently of normal probe samples.

Will add more items as i find them :p

**Comment by TitusLabs** [comment]
Yes, they are already documented in short. But I'm already on this to make them all overwriteable...

**Comment by TitusLabs** [comment]
Code and documentation are adapted now.

**Comment by th3fallen** [comment]
@TitusLabs  Looks like the fast first probe and sample count isn't applied to the probe in the middle of the bed. Only the endstop and probe samples

**Comment by TitusLabs** [comment]
hm, for me, it does.. you really activated this feature?

**Comment by th3fallen** [comment]
yep this is my config atm

```[z_calibration]
switch_offset: 0.435  # using SSG-5H
max_deviation: 1.5
speed: 80             # the moving speed in x and y
samples: 2
probing_first_fast: true
probe_nozzle_x: 95   # coordinates for clicking the nozzle on the z-endstop
probe_nozzle_y: 300
probe_switch_x: 90   # coordinates for clicking the probe's switch on the z-endstop
probe_switch_y: 280
probe_bed_x: 150      # coordinates for probing on the print surface (the center point)
probe_bed_y: 150```

and the probe in the middle of the bed only samples 1 fast time

**Comment by TitusLabs** [comment]
the samples property will not apply to the probing on the bed since I just call the probe there which is configured in the [probe] section. so, you mean only one sample? I think, you configured one sample on the probe ...but is it clicking twice on the bed?

**Comment by th3fallen** [comment]
Ah ok. That makes sense. But the fast first probe shouldn't apply to that sample then if there's only 1 sample configured right?

**Comment by TitusLabs** [comment]
yes, the fast first probe is not applied to any sample list at all!
