### ISSUE TITLE
Probe hits bed if retraction is smaller than new (negativ) offset

### ISSUE THREAD

**Issue by TravisWilder** [protoloft/klipper_z_calibration#10]
Hello

Example: Retract 0.2
After Probing on the bed the head move to the new offset.
If the Offset is bigger than the retract (i.e. -0.3) the probe will hit the bed and if  the next move will
detect the probe as docked (as the probe triggered)

One way would be to increase the retract to a value which is save.
But best way the script should check and not move the head lower then the retract after probe

Thanks for considering

**Comment by TitusLabs** [comment]
With 0.8.0, I removed the MOVE=1 parameter. There will be no move for correcting the position anymore. This should be safe now!
