### ISSUE TITLE
nozzle_xy_position:  safe_z_home  - safe_z_home is not used with Klicky probe. Can it take values from Klicky probe variables??

### ISSUE THREAD

**Issue by PhilBaz** [protoloft/klipper_z_calibration#107]
nozzle_xy_position: 

When using Klicky probe 'safe_z_home'  is commented out. Klicky probe has its own z_homing override routine and x,y variables,
'variable_z_endstop_x: '& 'variable_z_endstop_y: '     

It would be great if the values for nozzle_xy_position: could be inferred from the Klicky variables. I imagine a large number of users are using the klicky probe with z_calibration.

As it is currently the same values must be input to both the klicky variables as well as nozzle_xy_position: . This would be a nice little qol addition. 

ps...thanks for your work! My Voron wouldn't be nearly as good without it :)

**Comment by TitusLabs** [comment]
That's the problem with configurations and macro variables.

The only way I can think of is to provide a command parameter like `CALIBRATE_Z SWITCH_XY_POSiTION=x,y`. Then, you can use your macro variables while calling the calibration in your PRINT_START. Or even overwrite the CALIBRATE_Z command with a macro to set this parameter. Then you are able to call CALIBRATE_Z manually without the position :thinking:

**Comment by PhilBaz** [comment]
@TitusLabs 

Hi, thanks for the reply. If there is some technical reason the implementation is not simple then I get it. I cant code, but think I get what you are saying. Because of the way the variables are established its not easy to just reference them. 

That's a shame as both klicky and z_calibration are referring to the the exact same coordinates and if you forget to update one or the other there could be problems. 

Maybe I should raise this issue with the person who maintains klicky's code?

**Comment by TitusLabs** [comment]
This is not related to the calibraton. It's a common "problem". But, I don't think that you will be successful. The configuration is fixed - if not, there must be a command to change it.

I will add more parameters to the CALIBRATE_Z command :+1:

**Comment by PhilBaz** [comment]
@TitusLabs 

Awesome.... thanks again for such a useful tool. :)

**Comment by PhilBaz** [comment]
After connecting with the guy who made/maintains Klicky on discord there was a solution that worked for me. 

Klicky has its own homing override macro. But if you are not using Klicky as a virtual_Z_endstop  there does not appear to be any need to use it. So I just deleted it, restored safe_Z homing and then let Z_calibration take the default coordinates for x,y. Done!
