### ISSUE TITLE
Unknown command: CALIBRATE_Z

### ISSUE THREAD

**Issue by fryc88** [protoloft/klipper_z_calibration#111]
Installed as per docs, just cloned GIT and used script to install, nothing happens after that.

![image](https://github.com/protoloft/klipper_z_calibration/assets/50572708/90b1ad83-bd9e-4b3b-9804-55f2f7a4bc5f)
![image](https://github.com/protoloft/klipper_z_calibration/assets/50572708/f9a6f1a7-c22c-4f38-a902-e23523de9c5e)

However Z calibrate comes up in update manager, so at least that part is being installed.

Also z_calibration.py symlink is in extras directory
![image](https://github.com/protoloft/klipper_z_calibration/assets/50572708/18378b91-662c-4e5d-994b-8af5d19a49fe)

Any clues?

**Comment by zsmbrvr** [comment]
@fryc88 how did you fix this?
