### ISSUE TITLE
Voron Tap support

### ISSUE THREAD

**Issue by Zephyrus67** [protoloft/klipper_z_calibration#126]
I wonder if this will be able to work with Voron Tap?

**Comment by Villiem** [comment]
Why would you need it? With tap the nozzle is your probe, you can change nozzles, build plate and it won´t matter

**Comment by TitusLabs** [comment]
We already had that question here #124 

If your tap is not reliable, then there seems to be an issue with your mechanics. Or it could be that you are using an electronic sensor which triggers differently with increasing heat..
