### ISSUE TITLE
Homing instance has no attribute 'get_stepper_trigger_positions' (breaking change in Klipper?)

### ISSUE THREAD

**Issue by NameOfTheDragon** [protoloft/klipper_z_calibration#13]
It looks like today's Klipper commit (65ed55a43be0b995fde2d620ea838352efa7afb8) might have a breaking change that is killing the z_calibrate logic. When I home all axes, it fails when homing the Z axis with:
![image](https://user-images.githubusercontent.com/1268490/130141067-6f3a2a3a-03b4-4d3f-bbe7-88f2ea0e081d.png)

In Klippy.log...
![image](https://user-images.githubusercontent.com/1268490/130141117-127b6a9d-2188-4cbf-8622-cfad1a9ea95f.png)

I rolled back my Klipper install to an earlier commit and the problem went away.

**Comment by Vassssko** [comment]
https://github.com/KevinOConnor/klipper/issues/4600#issue-975358446

**Comment by Vassssko** [comment]
> It looks like today's Klipper commit (65ed55a43be0b995fde2d620ea838352efa7afb8) might have a breaking change that is killing the z_calibrate logic. When I home all axes, it fails when homing the Z axis with:
> ![image](https://user-images.githubusercontent.com/1268490/130141067-6f3a2a3a-03b4-4d3f-bbe7-88f2ea0e081d.png)
> 
> In Klippy.log...
> ![image](https://user-images.githubusercontent.com/1268490/130141117-127b6a9d-2188-4cbf-8622-cfad1a9ea95f.png)
> 
> I rolled back my Klipper install to an earlier commit and the problem went away.

Found the problem were most likely because of outdated z_calibration.py issue. Please doublecheck you have updated z_calibration.py, mind the following: https://github.com/protoloft/klipper_z_calibration#moonraker-updater. Current z_calibration.py have following strings commented:
![image](https://user-images.githubusercontent.com/80907968/130204083-d797ced0-fb0d-4a67-8444-67c602a12d28.png)

**Comment by DoritosVodka** [comment]
I had the same issue. Found re-running the z_calib install again corrected the files/issue... Tied to this moonraker update.

https://github.com/protoloft/klipper_z_calibration#moonraker-updater

**Comment by NameOfTheDragon** [comment]
@Vassssko @DoritosVodka You guys were not wrong. I had auto-updated enabled via Fluidd and Moonraker, but as you guessed it looks like it was not updating the file correctly in the Klipper directory. I have now run the install script and it has generated a soft link. I have been able to update Klipper to the offending release and it's now all working again. I guess this can be closed now?

It would be really handy if it were possible to generate some sort of message during the auto-update process, like "Manual steps required" or something. I don't know the workings of the update process at all so don't know if that's even possible, but might be worth a look to save others from the bear trap that I fell into.
