### ISSUE TITLE
If no Bed Mesh, it uses Z endstop height as Zero Position

### ISSUE THREAD

**Issue by maxime-granger** [protoloft/klipper_z_calibration#132]
For the past few weeks, if my print does not have a bed mesh  it uses the the Z-Endstop height as the zero position. 
Not sure if it is an issue or me not setting it up correctly. 
I have used bed-position argument withing [calibrate_z] but I get an error message.
Then I used bed_xy_position: argument, without any success.  

What I don't understand is even if a bed mesh is not performed it probes in the middle of the print area but still uses the value from the z-Endstop 

If you could direct me in the correct direction, it would very appreciated. 

Thank you.

**Comment by TitusLabs** [comment]
Have you already figured this out? I'm not sure what you mean with value from z-endstop. If you configure the bed_xy_position, it will use this value - if not, it will use it from the mesh configuration. This is independent from any performed mesh. And, the position on the bed is always corrected by the offsets from the probe section. So, it's actually the probe hitting the middle of the bed and not the nozzle.
