### ISSUE TITLE
At end of calibration i get a "unknown command"

### ISSUE THREAD

**Issue by Experiment4** [protoloft/klipper_z_calibration#135]
5:47:54 // Unknown command:"DETACH_PROBE"
15:47:54 // probe: TRIGGERED
15:47:48 

Config section..says
[z_calibration]
nozzle_xy_position:  208,293 # <X,Y position for clicking the nozzle on the z endstop - not needed if [safe_z_home] is used>
switch_xy_position:  208,268 # A X, Y coordinate (e.g. 100,100) of the probe's switch body, clicking on the z endstop.
bed_xy_position:     150,150 #<X,Y position for probing the bed, for instance the center point - not needed if mesh with zero_reference_position is used>
switch_offset:       0.4 # <offset of the switch trigger (read the Switch Offset section!)>
start_gcode:          attach_probe #<macro name for attaching the probe>
before_switch_gcode:  attach_probe #<macro name for attaching the probe AFTER probing the nozzle>
end_gcode:            dock_probe #<macro name for docking the probe>

**Comment by thebrettman73** [comment]
**_For me_**, this was coming from "klicky-calibrate_z.cfg":

[gcode_macro CALIBRATE_Z]
rename_existing: BASE_CALIBRATE_Z
gcode:
    {% set bed_position = params.BED_POSITION|default('None') %}
    CG28                         # can also be a conditional homing macro
    M117 Z-Calibration..
    #ATTACH_PROBE                # a macro for fetching the probe first     **<---HERE**
    {% if bed_position != 'None' %}
      BASE_CALIBRATE_Z BED_POSITION={bed_position}
    {% else %}
      BASE_CALIBRATE_Z
    {% endif %}
    #DETACH_PROBE                # and parking it afterwards (or DOCK_PROBE in klicky macros)    **<---HERE**
    M117

I just commented out the attach and detach macros, as the are called correctly in the "[z_calibration]" config section.

**Comment by TitusLabs** [comment]
Yes, you need to call the correct macro name that you are using. Is this already solved?
