### ISSUE TITLE
Self updating script 

### ISSUE THREAD

**Issue by th3fallen** [protoloft/klipper_z_calibration#2]
No idea if you want to implement this but i added this to my moonraker.conf to add tracking of new versions of this lib

```
[update_manager client z-calibrate]
type: git_repo
origin: https://github.com/protoloft/klipper_z_calibration.git
primary_branch: main
path: /home/pi/klipper_z_calibration
```

then ssh'd in and did 
`ln -s /home/pi/klipper_z_calibration/z_calibration.py /home/pi/klipper/klippy/extras/z_calibration.py`

the only thing its lacking is a script to bounce the klipper service when it updates.

thought i'd share

**Comment by TitusLabs** [comment]
Sorry, this does not work at all as I thought it could do. Currently I don't have time for this...

**Comment by th3fallen** [comment]
Sorry I actually forgot to close this

**Comment by TitusLabs** [comment]
It is still an issue...
