### ISSUE TITLE
configuration/homing.cfg G0 Z2 F1500 is in absolute not relative mode

### ISSUE THREAD

**Issue by sprior** [protoloft/klipper_z_calibration#25]
Looking at configuration/homing.cfg:

Line 22 leaves the printer in absolute mode.
Line 38 the touches the nozzle to the z probe,
Line 39 then G0 Z2 F1500  which is intended to move the nozzle up, but if the z probe offset is more than 2mm it actually moves DOWN smashing into the Z probe.
I suggest adding a G91 just before line 39 as a fix.

**Comment by TitusLabs** [comment]
Many thanks! I have changed it :thumbsup:
