### ISSUE TITLE
Error: Unknown config object 'homing' after update

### ISSUE THREAD

**Issue by Frix-x** [protoloft/klipper_z_calibration#3]
Hello,
I updated today both Klipper and Z_calibration plugin and get this new error :
![image](https://user-images.githubusercontent.com/10575621/123148367-716f4a80-d460-11eb-90b8-121ebcd2b642.png)

I'll investigate further to find a fix and let you know.

**Comment by TitusLabs** [comment]
Ah, yes. I remember this. Someone already had this issue too. The problem is, that the order of the configuration sections matters...

**Comment by TitusLabs** [comment]
Thanks, should work in any configuration orders now!
