### ISSUE TITLE
Alternative way

### ISSUE THREAD

**Issue by TypQxQ** [protoloft/klipper_z_calibration#32]
Wanted to show an alternative way to do this with off the shelf hardware and only gcode commands.
I made the Knobprobe for probing Z offset between nozzle and Z-Probe.

https://youtu.be/fshmEMWxBHY

**Comment by medicusdkfz** [comment]
With this probing method you need a pretty flat print bed. But if your print bed is a little bit wobbly and you'll need a mesh compensation, then it's better to use a method like Klicky or BLT probe...
