### ISSUE TITLE
suggest adding a note about GCODE_RESTORE_STATE

### ISSUE THREAD

**Issue by garyd9** [protoloft/klipper_z_calibration#41]
It appears that if a person has a print_start that saves the gcode state (SAVE_GCODE_STATE name=whatever), does a CALIBRATE_Z, and then follows the CALIBRATE_Z with a restoration of gcode state (RESTORE_GCODE_STATE name=whatever), that the offsets set by CALIBRATE_Z are lost.  

I'd suggest adding a note in the documentation that calls to CALIBRATE_Z should be done outside of SAVE/RESTORE gcode state.

**Comment by TitusLabs** [comment]
Yes, this is correct! I thought, that I did it somewhere... I will add it, thanks :+1:

**Comment by TitusLabs** [comment]
done!
