### ISSUE TITLE
Dummy service not necessary?

### ISSUE THREAD

**Issue by gongloo** [protoloft/klipper_z_calibration#43]
I'm having trouble understanding the need for the dummy service. I'm no moonraker expert, but it would appear that it's not necessary to have a dummy service for update_manager to work?

**Comment by TitusLabs** [comment]
Unfortunately, yes! Meanwhile, there is a new flag to disable a system service reload. But, there is still no other way to reload Klipper after an update. But Arksine from Moonraker is aware of it...
