### ISSUE TITLE
how to access z_offset value that is stored in [SAVE_CONFIG] section of printer.cfg

### ISSUE THREAD

**Issue by hitmusic100** [protoloft/klipper_z_calibration#54]
Am considering adjusting calibrate_z.py a little, and would like to access z_offset from printer.cfg (the value prior to any SAVE_CONFIG).  Please would you let me know how to do this from within calibrate_z.py - thanks!

This is a screenshot of the value's location
![image](https://user-images.githubusercontent.com/54537765/162742783-76b21ae9-624b-4411-a251-2f66f2b71c5f.png)

**Comment by TitusLabs** [comment]
This should be just `self/helper.printer.lookup_object('probe').z_offset` ..what is your idea with that value?

**Comment by hitmusic100** [comment]
Thanks TitusLabs, for this - I can't wait to try it out (am away from home atm) - will certainly update this thread, br
