### ISSUE TITLE
Retry calibration if Deviation too high

### ISSUE THREAD

**Issue by everything-tech-related** [protoloft/klipper_z_calibration#55]
Most times it doesnt work on the first try. However when i run it again its perfect. A retry calibration option would be nicewould be nice

**Comment by TitusLabs** [comment]
Don't you use samples and samples_tolerance_retries? That should do the trick! And maybe probing_first_fast too...

**Comment by NyxCode** [comment]
[you might wanna take a look at my solution for this](https://github.com/protoloft/klipper_z_calibration/issues/58#issuecomment-1113965970)
