### ISSUE TITLE
Docking issue

### ISSUE THREAD

**Issue by rmilyard** [protoloft/klipper_z_calibration#60]
I could use some ideas what look for on this.  The v2.4 was printing fine and all worked.  I updated all my file moonraker, klipper and z_calobration.  So after that looks like now when tried to dock probe is drops down to far.  Did something change I need to look for?   https://share.icloud.com/photos/0c63r2jqQNJtYrYf1V1DQnlfg
[iCloud.com](https://share.icloud.com/photos/0c63r2jqQNJtYrYf1V1DQnlfg)

**Comment by TitusLabs** [comment]
Hi, sorry for late answer.. have you already solved your issue?
