### ISSUE TITLE
Attach & Detach Probe Documentation Macro has simple spelling mistake

### ISSUE THREAD

**Issue by evader** [protoloft/klipper_z_calibration#62]
Love your solution. Simple mistake under documentation for Attach & Detach Probe Macro on your main page.
You have CG28 instead of G28. Hope this helps and many many thanks for your tremendous work.

![Screen Shot 2022-05-10 at 9 18 58 pm](https://user-images.githubusercontent.com/79675315/167637763-d1cebb01-4ce5-439b-b3fb-35d5d99e853a.png)

Hoping the macro should be like the following.

[gcode_macro CALIBRATE_Z]
rename_existing: BASE_CALIBRATE_Z
gcode:
    {% set bed_position = params.BED_POSITION|default('None') %}
    G28 
    M117 Z-Calibration..
    ATTACH_PROBE                # a macro for fetching the probe first
    {% if bed_position != 'None' %}
      BASE_CALIBRATE_Z BED_POSITION={bed_position}
    {% else %}
      BASE_CALIBRATE_Z
    {% endif %}
    DETACH_PROBE                # and parking it afterwards (or DOCK_PROBE in klicky macros)
    M117

**Comment by jangrewe** [comment]
It is: https://docs.vorondesign.com/community/macros/macros/120decibell.html

**Comment by TitusLabs** [comment]
Yes, that is the conditional homing macro. But sorry, that is not clear in this context... I will change that :+1:
