### ISSUE TITLE
Auto-calibration issue with probe position in Z not being calculated properly

### ISSUE THREAD

**Issue by fmonaca** [protoloft/klipper_z_calibration#67]
I have a weird issue with auto-z-calibration... shouldn't the actual probe height from the bed be considered every time the offset is calculated? I had to move the probe up on my printer and the whole first layer was messed up. Once the actual switch Z offset (in my case 0.44mm) is set into the configuration and the whole calibration works hitting the Z endstop with the nozzle, then the probe body etc., the script should just do the math, right? At least that is how it is working on my Voron. On my other printer, though, the (Quickdraw) probe is connected to the fan shroud, so when I adjusted the vertical position of the shroud, I realised that after a Z calibration the offset was wrong by the distance I moved the shroud/probe position by. I dit another test and I swapped the nozzle. The tip of the new nozzle was slightly lower than the old (luckily only 0.3mm or so). Again, after a calibration, the first layer was too low by the same amount.

**Comment by TitusLabs** [comment]
Hi, sorry for the late answer. Is this still a problem for you? I'm not sure what you mean by adjusting the position of the shroud... So, it just determines the heights of the nozzle, switch and bed and puts them in relation to each other - anything else does not matter.
