### ISSUE TITLE
ERROR_NO_PROBE error message

### ISSUE THREAD

**Issue by Tircown** [protoloft/klipper_z_calibration#7]
The error message is the same for a missing `[probe]` section and a non attached probe because both use the same constant name.
https://github.com/protoloft/klipper_z_calibration/blob/a814376b0258ea3b419e63fc97b73ecfc010a128/z_calibration.py#L8-L9
https://github.com/protoloft/klipper_z_calibration/blob/a814376b0258ea3b419e63fc97b73ecfc010a128/z_calibration.py#L14
https://github.com/protoloft/klipper_z_calibration/blob/a814376b0258ea3b419e63fc97b73ecfc010a128/z_calibration.py#L83-L84
https://github.com/protoloft/klipper_z_calibration/blob/a814376b0258ea3b419e63fc97b73ecfc010a128/z_calibration.py#L134-L135

**Comment by TitusLabs** [comment]
Yes, thanks! I already noticed this too.. it's fixed in 0.8.0 :-)
