### ISSUE TITLE
Clearing up some confusion

### ISSUE THREAD

**Issue by AndrewEllis93** [protoloft/klipper_z_calibration#75]
We frequently have users in the Voron Discord who are very confused by how this Z calibration works, and as a result either struggling to set it up, or setting it up incorrectly.

Particularly users who have no idea that they need a good base Z calibration first, and will set the `max_deviation` very high instead. Then, if calibration ever fails, they will dig a trench through their PEI.

I think it would clear up a lot of confusion if it were made clear in the documentation/naming that it's auto *baby stepping* rather than auto *calibration*.  That might indicate to more people that they need to still use Z_ENDSTOP_CALIBRATE and have a reasonable `position_endstop`.

**Comment by TitusLabs** [comment]
It's finally on it's way... :+1:

**Comment by TitusLabs** [comment]
Finally.. done!
