### ISSUE TITLE
Section 'z_calibration' is not a valid config section

### ISSUE THREAD

**Issue by 76900289** [protoloft/klipper_z_calibration#77]
klipper      v0.11.0-41-g9b60daf6
Section 'z_calibration' is not a valid config section?

**Comment by gdachs** [comment]
That is not an issue. Your configuration is wrong. Most likely you didn't add `[include z_calibration.cfg]` to your printer.cfg.
Before you open an issue on github, always triple check that the problem is not on your side.

**Comment by 76900289** [comment]
Added. It is a problem after updating KLIPPER

**Comment by 76900289** [comment]
It is normal before updating

**Comment by gdachs** [comment]
I use the same Klipper version with z_calibration, no problems. Upload your klippy.log.

**Comment by 76900289** [comment]
[klippy.txt](https://github.com/protoloft/klipper_z_calibration/files/10299742/klippy.txt)

**Comment by gdachs** [comment]
what gives `ls -l ~/klipper/klippy/extras/z_calibration.py`

**Comment by 76900289** [comment]
I see. The update uninstalled this file. Thank you very much

**Comment by gdachs** [comment]
How did you update? Anyway, so you can close this issue.

**Comment by 76900289** [comment]
![1111](https://user-images.githubusercontent.com/61819114/209467033-45254bd7-a514-4b5c-b4fb-837bb3b10223.jpg)
here

**Comment by aCtionBR** [comment]
Hello I have just executed an update all in my configuration manager. I had my z_calibration working perfect before and now the system is presenting this same error after this update. I am adding a print of the error and a copy of klippy.log. 
Can you please help me to identify what is wrong?

![Capturar](https://github.com/protoloft/klipper_z_calibration/assets/19878796/83f09f2f-6075-4b49-90d9-818ef14800d6)

[klippy.log](https://github.com/protoloft/klipper_z_calibration/files/11646567/klippy.log)

**Comment by aCtionBR** [comment]
I solved it. 
I have seen a lot of comments in other foruns about this problem, but none of them commented what solved my problem, so I am adding below what was the problem. Maybe it helps others.
There has been an update on the format accepted in z_calibration.cfg file. I have not looked into when it happend, what I learned is that the old configuration directives (like probe_nozzle_x: xxx) is no longer accepted. You have to adapt your z_calibration.cfg file to the new standard that uses nozzle_xy_position insted of  probe_nozzle_x and  probe_nozzle_y.

I got it from the configuration file presented at https://github.com/protoloft/klipper_z_calibration/wiki/How-To-Configure-It. Then I researched for some examples of z_calibration.cfg file in the internet to double check.
