### ISSUE TITLE
offset calculate

### ISSUE THREAD

**Issue by Reneeetje** [protoloft/klipper_z_calibration#78]
My position of endstop is 8 mm above bed, i own a ender 5 plus and that is the only way i can use this and autoz.
But auto z is performing good, does al the calculation. But the offset is always wrong and i cannot figger out why.
I did position_endstop = 8, afther calibratez and g90 g0 z10 my nozzle is way to close to the bed.

// Z-CALIBRATION: ENDSTOP=8.000 NOZZLE=8.009 SWITCH=13.379 PROBE=6.777 --> OFFSET=0.786250

what could this be? is there another offset i have to use?

**Comment by Nelus82** [comment]
I'm having the same problem. My endstop is the same height as my bed (position_endstop = 0).
Everytime when I do a Z calibration it gives me a Z-Offset: 1.2

The probe z_offset does nothing.

**Comment by RcTomcat1** [comment]
I am experiencing the same issues after updating klipper and moonraker to the latest versions...Yesterday my printer was doing fine, today it crashes the nozzle

**Comment by LaRenard** [comment]
I've recently added a mod to a printer and set up auto-z but it appears to be doing the same behaviour described here, my endstop is 4mm above the bed which I've set in stepper_z config
Manually doing the probe calibration I get 4.x mm which I added to my probe config but the auto-z is always touching the bed when the print starts:

`Z-CALIBRATION: ENDSTOP=4.015 NOZZLE=4.012 SWITCH=8.088 PROBE=4.663 --> OFFSET=0.137500`

**Comment by TitusLabs** [comment]
Have you been able to solve this in the meantime?

I have not observed such behavior with my printers. Especially since the plugin should be very independent from the rest of Klipper at its core. And it can't be related to a Moonraker update.

A correct auto calibration does not depend on the values z endstop position or z probe offset - although it is advisable to set them reasonably accurately.

**Comment by Nelus82** [comment]
Yes, the problem was the heightmap. It was 1.2 mm off. I had to create a good mesh at 0 (with probe z_offset). And then the z calibration is almost perfect. 

You can also disable auto load mesh.

**Comment by TitusLabs** [comment]
Ok, great! Most problems are related to bed mesh. Then I will close this ticket..
