### ISSUE TITLE
Probe not attached error - incorrect

### ISSUE THREAD

**Issue by DevInOrbit** [protoloft/klipper_z_calibration#80]
I just updated klipper ( v0.11.0-99-g56444815 )  and to the latest klipper_z_calibration library code ( v0.9.2-0-gf212b40 ) using the Fluidd update interface. Up till now the klicky and this library have worked great.

Now when it gets to the point of moving to the center of the bed it stops with "Probe switch not closed - Probe not attached?" 

I have verified there are no wiring/mechanical issues at play. Could this be related to the code issue referenced here?:
https://github.com/nielsvz/klipper_dockable_probe/issues/1

Sample Log:
 11:28:52  // Attaching Probe
11:28:52  // moving to a safe Z distance
11:28:57  // probe: open
11:29:00  // probe at 233.000,324.000 is z=5.086750
11:29:02  // probe at 233.000,324.000 is z=5.090500
11:29:04  // probe at 233.000,324.000 is z=5.091750
11:29:06  // probe at 233.000,324.000 is z=5.090500
11:29:09  !! Probe switch not closed - Probe not attached?
11:29:09  !! Probe switch not closed - Probe not attached?
11:29:09  !! Probe switch not closed - Probe not attached?

**Comment by vajonam** [comment]
This is what I am using with kicky, works a treat. 

this is for my 300mm Trident. 

```
[z_calibration]
nozzle_xy_position:  171.50, 298.50
switch_xy_position:  171.00, 277
switch_offset:        0.48
start_gcode:          ATTACH_PROBE
before_switch_gcode:  ATTACH_PROBE
end_gcode:            DOCK_PROBE
max_deviation: 6.0
speed: 200
```

also make sure in your klicky config you have

```
variable_z_endstop_x:         171.50
variable_z_endstop_y:         298.50
```

**Comment by TitusLabs** [comment]
This is strange. In 0.9.2 I moved the probe check from the beginning to just before the probing. So if you lose it on the way to that point, you will be noticed. 
This error means that the probe is not closed and therefore triggered. The probe must connect the input pin to GND. And if triggered, it will open (normally closed). This is a condition for the plugin to work and means more safety. If this is the case, maybe your probe contact is loose?

**Comment by TitusLabs** [comment]
Any news? Otherwise, I will close this...

**Comment by tijnfaas** [comment]
I have this same issue. Probe is working correctly (checked every aspect of this and rewired it, just in case).
The issue happens to me when the z-switch has been probed and the distance to the kicky base should be measured. It lower 1 or 2 millimeters and then throws the error "Probe switch not closed - Probe not attached?"

What other or more precise information do you need to troubleshoot this issue?

**Comment by TitusLabs** [comment]
Is this still an issue? Otherwise, I will close this ticket...
