### ISSUE TITLE
Question / Feature request: CNC style probing

### ISSUE THREAD

**Issue by dropax** [protoloft/klipper_z_calibration#86]
I've seen the use of the tool itself in a CNC router probing against a simple conductor to calibrate z.
I'm building a Voron 0.2 with the endstop at z_max, the hotend/heatsink is electrically isolated. Why not tie the heatsink to a controller input and probe against a plain grounded bolt near the bed?

The only downsides I can think of:
- risk of mechanical damage if the nozzle is cold and some plastic residue can't squish away and prevents the circuit from closing
- risk of frying the controller if a "life" heater wire somehow touches the heatsink (a CAN equipped toolhead should at least protect the mainboard)

I'm ready to take these risks. If I want to use z_calibration.py the probe must touch the bolt with the actual switch and not with its body and thus the probe becomes the trigger instead of the z-endstop. I found this piece of code at line 331/332:
` # probe the body of the switch`
`switch_zero = self._probe_on_site(self.z_endstop,
                                          self.helper.switch_site,
                                          True)`

Would it suffice to replace `self.z_endstop` with `self.probe` and set `switch_offset` to 0?

**Comment by TitusLabs** [comment]
You can do this. But, I don't get it why you should do this. What are you trying to accomplish? And the risk with the plastic isolating the nozzle is really high. The bottom line is that the z endstop pin is just that, too. The only difference is that it is a switch for the reasons mentioned above.

And you don't need this plugin to do this - this will not work. Just use it as your probe.
