### ISSUE TITLE
Installation command does not work

### ISSUE THREAD

**Issue by rschaeuble** [protoloft/klipper_z_calibration#92]
When using the moonraker update manager, according to the documentation the following command has to be executed:
`ln -sf klipper_z_calibration/z_calibration.py ~/klipper/klippy/extras/z_calibration.py`

However, that creates an invalid link. It has to read `ln -sf ~/klipper_z_calibration/z_calibration.py ~/klipper/klippy/extras/z_calibration.py` (a `~/` before the target path).

I would have created a pull request if I knew how to with a wiki.

**Comment by TitusLabs** [comment]
Oh, thanks for the hint! Yes, github wiki was not the best choice. I have corrected it :+1:
