### ISSUE TITLE
Slight Change in z_calibration.cfg

### ISSUE THREAD

**Issue by AustinTylerDean** [protoloft/klipper_z_calibration#99]
I get a parsing error from 'safe_z_height: 2 * z_offset from "probe:z_offset" section'

I'm no good with programming, so maybe it's an easy fix.

**Comment by AustinTylerDean** [comment]
When the value from the initial unconfigured z_calibration.cfg reads "default from "xxx" section, am I being dumb for thinking the parser knows what to do with that?

**Comment by AustinTylerDean** [comment]
Unless there's a value, you need to # the line or put a value in.

**Comment by TitusLabs** [comment]
Correct, it's the default value the script uses if you do not configure a value for this property :+1: 
But, you're right, I forgot the "default" there..
